config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get '/', to: 'tasks#index'
  resources :tasks do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :labellings, only: [:create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :labelling_tasks, through: :labellings, source: :task
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :task_name, presence: true, uniqueness: true
  validates :detail, presence: true, length:{maximum:50}
  validates :deadline, presence: true
  scope :task_name, -> (task_name) { where('task_name LIKE ?', "%#{task_name}%") }
  scope :status, -> (status) { where(status: status) }
  enum priority: { 高:0, 中:1, 低:2 }
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings, source: :label
  accepts_nested_attributes_for :labels, allow_destroy: true
  #paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tasks, dependent: :destroy
  before_destroy :delete_check

  private
  def delete_check
    if self.admin?
      if User.where(admin: :true).count == 1
      throw(:abort)
      end
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :set_user, only:[:show, :edit, :update, :destroy]
before_action :authenticate_user

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if params[:back]
      render :new
    else
      if @user.save
        redirect_to admin_users_path, notice: "ユーザーを作成しました"
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice:"ユーザーを編集しました"
    else
      render :new
    end
  end

  def show
    @user_tasks = User.where(id:params[:id])
    @user_task = User.where(id:params[:id]).count
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice:"ユーザーを削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authenticate_user
    @users = User.all
    unless logged_in? && current_user.admin == true
      redirect_to tasks_path, notice:"管理者以外はアクセスできません"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :basic_authenticate
  before_action :authenticate_user, only: [:index]

  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def basic_authenticate
    if Rails.env == "production"  #本番環境のみ適応させる
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['USERNAME'] && password == ENV['PASSWORD']
      end
    end
  end

  #def basic_authenticate
    #authenticate_or_request_with_http_basic do |username, password|
      #username == 'manyo_test' && password == 'manyo_password'
    #end
  #end

  def authenticate_user
    unless logged_in?
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.where(user_id:current_user.id).order(created_at: :desc).page(params[:page]).per(10)
    if params[:deadline]
      @tasks = Task.where(user_id:current_user.id).order(deadline: :desc).page(params[:page]).per(10)
    elsif params[:created_at]
      @tasks = Task.where(user_id:current_user.id).order(created_at: :desc).page(params[:page]).per(10)
    elsif params[:priority]
      @tasks = Task.where(user_id:current_user.id).order(priority: :asc).page(params[:page]).per(10)
    end

    @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?

    if params[:task_name].present? && params[:status].present?
      @tasks = Task.where(user_id:current_user.id).task_name(params[:task_name]).status(params[:status]).page(params[:page]).per(10)
    elsif params[:task_name].present?
      @tasks = Task.where(user_id:current_user.id).task_name(params[:task_name]).page(params[:page]).per(10)
    elsif params[:status].present?
      @tasks = Task.where(user_id:current_user.id).status(params[:status]).page(params[:page]).per(10)
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path, notice: "タスクを作成しました"
      else
        render :new
      end
    end
  end

  def show
    @labels = @task.labels
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice:"タスクを編集しました"
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました"
  end

  def confirm
    @task = current_user.tasks.build(task_params)
    @labels = @task.labels
    render :new if @task.invalid?
  end

  private
  def task_params
    params.require(:task).permit(:task_name, :detail, :deadline, :status, :priority, label_ids: [] )
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user, only: [:new]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user.name == current_user.name
      redirect_to tasks_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def authenticate_user
    if logged_in?
      flash[:notice] = t('notice.login_needed')
      redirect_to tasks_path
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def admin_choose_new_or_edit
    if action_name == "new"  || action_name == "create"
      admin_users_path
    elsif action_name == "edit"
      admin_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/task_labels_helper.rb
module TaskLabelsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == "new"  || action_name == "create"
      confirm_tasks_path
    elsif action_name == "edit"
      task_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true, url: admin_choose_new_or_edit) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin %>
  <%= f.check_box(:admin, {:checked => false}, checked_value = "true", unchecked_value = "false") %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb
<div class="wrapper">
  <h4 class="title">ユーザー一覧</h4>
  <th class="col_md-1 offset-md-10 new_task_button"><button type="button" class="btn btn-primary"><%= link_to "新規作成", new_admin_user_path, class:"new_task_button_text" %></button>
  <table class="container">
    <tr class="row">
      <th class="col-md-1 offset-md-5 index_items">ユーザー</th>
      <th class="col-md-2 index_items">メールアドレス</th>
      <th class="col-md-1 index_items">タスク数</th>
      <th class="col-md-1 index_items">管理者権限</th>
      <th class="col-md-1 index_items"></th>
      <th class="col-md-1 index_items"></th>
      <th class="col-md-1 index_items"></th>
    </tr>
    <% @users.each do |user| %>
    <tr class="row task_row">
      <td class="col-md-1 offset-md-4 index_items"><%= user.name %></td>
      <td class="col-md-2 index_items"><%= user.email %></td>
      <td class="col-md-1 index_items"><%= user.tasks.count %>
      </td>
      <td class="col-md-2 index_items"><% if user.admin == true %>有<% else %><% end %></td>
      <td class="col-md-1 index_items "><button type="button" class="btn btn-primary"><%= link_to "詳細", admin_user_path(user.id), class:"index_link"%></button></td>
      <td class="col-md-1 index_items"><button type="button" class="btn btn-success"><%= link_to "編集", edit_admin_user_path(user.id), class:"index_link" %></td>
      <td class="col-md-1 index_items"><button type="button" class="btn btn-danger"><%= link_to "削除", admin_user_path(user.id), method: :delete,data: { confirm: '本当に削除していいですか？' }, class:"index_link" %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/users/new.html.erb
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細画面</h1>
<p>ユーザー名: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>
<p>このユーザーの投稿:</p>

<table class="container">
  <tr class="row">
    <th class="col-md-2 offset-md-5 index_items">タスク名</th>
    <th class="col-md-2 index_items">詳細</th>
    <th class="col-md-1 index_items">期限</th>
    <th class="col-md-1 index_items">状況</th>
    <th class="col-md-1 index_items">優先度</th>
  </tr>
  <% @user_tasks.each do |user| %>
    <% user.tasks.each do |user_task| %>
  <tr class="row task_row">
    <td class="col-md-2 offset-md-5 index_items"><%= user_task.task_name %></td>
    <td class="col-md-2 index_items"><%= user_task.detail %></td>
    <td class="col-md-1 index_items"><%= user_task.deadline %></td>
    <td class="col-md-1 index_items"><%= user_task.status %></td>
    <td class="col-md-1 index_items"><%= user_task.priority %></td>
    <% end %>
  </tr>
</table>
<button type="button" class="btn btn-success"><%= link_to "編集", edit_admin_user_path(user.id), class:"index_link" %>
<button type="button" class="btn btn-danger"><%= link_to "削除", admin_user_path(user.id), method: :delete,data: { confirm: '本当に削除していいですか？' }, class:"index_link" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><a href="#">タスク管理アプリ</a></li>
        <li><a href="#">トップページ</a></li>
      </ul>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
    <footer>
      <p>運営会社DIVE INTO CODE株式会社</p>
      <p>© 2015-2016 DIVE INTO CODE Corp.</p>
    </footer>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true, url: choose_new_or_edit) do |form| %>
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2><%= @task.errors.count %><%= t('errors.messages.error_number') %></h2>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">タスクの作成</div>
    <div class="panel-body">
      <form class="form-horizontal">
        <div class="form-group task_new">
          <label class="col-md-3 control-label"><%= t('attributes.task.task_name') %></label>
          <div class="col-md-9 new_form">
            <%= form.text_field :task_name, class:"form-control", type:"string" %>
          </div>
        </div>
        <div class="form-group task_new">
          <label class="col-md-3 control-label"><%= t('attributes.task.detail') %></label>
          <div class="col-md-9 new_form">
            <%= form.text_field :detail, class:"form-control", type:"text" %>
          </div>
        </div>
        <div class="form-group task_new">
          <label class="col-md-3 control-label"><%= t('attributes.task.deadline') %></label>
          <div class="col-md-9 new_form">
            <%= form.date_field :deadline %>
          </div>
        </div>

        <div class="form-group task_new">
          <label class="col-md-3 control-label"><%= t('attributes.task.status') %></label>
          <div class="col-md-9 new_form">
            <%= form.select :status, [["未着手","未着手"],["着手中","着手中"],["完了","完了"]], include_blank: "選択して下さい" %>
          </div>
        </div>
        <div class="form-group task_new">
          <label class="col-md-3 control-label"><%= t('attributes.task.priority') %></label>
          <div class="col-md-9 new_form">
            <%= form.select :priority, Task.priorities.keys.to_a, include_blank: "選択して下さい" %>
          </div>
        </div>

        <% Label.all.each do |label| %>
          <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
          <%= form.label :label_ids, label.name, value: label[:id] %>
        <% end %>

      </form>
        <div class="form-group task_new">
          <div class="col-md-12">
            <%= form.submit %>
            <% end %>
          </div>
        </div>
    </div>
  </div>
  <%= link_to t('attributes.task.backto_index'), tasks_path %>
</div>

app/views/tasks/confirm.html.erb
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading"><%= t('attributes.task.Please Confirm') %></div>
    <div class="panel-body">
        <div class="row showpage_item">
          <%= form_with(model: @task, local: true) do |form| %>
          <label class="col-md-5 showpage_label">
            <%= form.hidden_field :task_name %>
            <%= t('attributes.task.task_name') %>
          </label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.task_name %>
          </div>
        </div>
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label">
            <%= form.hidden_field :detail %>
            <%= t('attributes.task.detail') %>
          </label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.detail %>
          </div>
        </div>
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label">
            <%= form.hidden_field :deadline %>
            <%= t('attributes.task.deadline') %>
          </label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.deadline %>
          </div>
        </div>
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label">
            <%= form.hidden_field :status %>
            <%= t('attributes.task.status') %>
          </label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.status %>
          </div>
        </div>
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label">
            <%= form.hidden_field :priority %>
            <%= t('attributes.task.priority') %>
          </label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.priority %>
          </div>
        </div>
        <div class="row showpage_item">
          <% @labels.each do |label| %>
            <span class="badge bg-secondary">
            <%= form.hidden_field :label_ids, multiple: true, value: label.id %>
              <%= label.name %>
            </span>
          <% end %>
        </div>
        <%= form.submit t('attributes.task.submit') %>
        <%= form.submit t('attributes.task.back'), name: "back" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<h4 class="title">タスク一覧</h4>
<table class="container">
  <tr class="row">
    <th class="col_md-6 new_task_button"><button type="button" class="btn btn-primary"><%= link_to t('attributes.task.create_task'), new_task_path, class:"new_task_button_text" %></button>
    <th class="col-md-6 index_search">
      <%= notice %>
      <%= form_with url: tasks_path, method: :get, local: true do |f| %>
        <%= f.text_field :task_name %>
        <%= f.select :status, [["未着手","未着手"],["着手中","着手中"],["完了","完了"]], include_blank: "選択して下さい" %>
        <%= f.submit '検索', name: nil %>
      <% end %>
    </th>
  </tr>
</table>

<table class="container">
  <tr class="row">
    <th class="col-md-2 index_items"><%= t('attributes.task.task_name') %></th>
    <th class="col-md-2 index_items"><%= t('attributes.task.detail') %></th>
    <th class="col-md-1 index_items"><%= t('attributes.task.detail') %></th>
    <th class="col-md-2 index_items"><%= t('attributes.task.deadline') %></th>
    <th class="col-md-1 index_items"><%= t('attributes.task.status') %></th>
    <th class="col-md-1 index_items"><%= t('attributes.task.priority') %></th>
    <th class="col-md-1 index_items"></th>
    <th class="col-md-1 index_items"></th>
    <th class="col-md-1 index_items"></th>
  </tr>
<% @tasks.each do |task| %>
  <tr class="row task_row">
    <td class="col-md-2 index_items"><%= task.task_name %></td>
    <td class="col-md-2 index_items"><%= task.detail %></td>
    <td class="col-md-1 index_items"><%= task.user.name %></td>
    <td class="col-md-2 index_items"><%= task.deadline %></td>
    <td class="col-md-1 index_items"><%= task.status %></td>
    <td class="col-md-1 index_items"><%= task.priority %></td>
    <td class="col-md-1 index_items "><button type="button" class="btn btn-primary"><%= link_to t('attributes.task.detail_page'), task_path(task.id), class:"index_link"%></button></td>
    <td class="col-md-1 index_items"><button type="button" class="btn btn-success"><%= link_to t('attributes.task.edit_page'), edit_task_path(task.id), class:"index_link" %></td>
    <td class="col-md-1 index_items"><button type="button" class="btn btn-danger"><%= link_to t('attributes.task.delete'), task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class:"index_link" %></td>
  </tr>
<% end %>
</table>
<%= paginate @tasks %>
<div class="container index_sort">
  <div class="row">
    <div class="col-md-3"><%= link_to t('attributes.task.Sort by Deadline'), tasks_path(deadline: "true") %></div>
    <div class="col-md-3"><%= link_to t('attributes.task.Sort by Create_time'), tasks_path(created_at: "true") %></div>
    <div class="col-md-3"><%= link_to t('attributes.task.Sort by Priority'), tasks_path(priority: "true") %></div>
    <div class="col-md-3">
      <%= form_with url: tasks_path, method: :get, local: true do |form| %>
        <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
        <%= form.submit 'Search', name: nil %>
      <% end %>
    </div>
  </div>
</div>

<%= link_to "管理者画面へ", admin_users_path %>

app/views/tasks/show.html.erb
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading"><%= t('attributes.task.Task Detail')%></div>
    <div class="panel-body">
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label"><%= t('attributes.task.task_name') %></label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.task_name %>
          </div>
        </div>
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label"><%= t('attributes.task.detail')%></label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.detail %>
          </div>
        </div>
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label"><%= t('attributes.task.deadline')%></label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.deadline %>
          </div>
        </div>
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label"><%= t('attributes.task.status')%></label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.status %>
          </div>
        </div>
        <div class="row showpage_item">
          <label class="col-md-5 showpage_label"><%= t('attributes.task.priority')%></label>
          <div class="col-md-6 offset-md-1 showpage_content">
            <%= @task.priority %>
          </div>
        </div>
        <% @labels.each do |label| %>
        <span class="badge bg-secondary">
          <%= label.name %>
        </span>
        <% end %>
      </div>
  </div>
  <%= link_to t('attributes.task.backto_index'), tasks_path %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス：<%= @user.email %></p>
<%= link_to "タスク一覧へ", tasks_path %>